version: 2.1
orbs:
  packer: salaxander/packer@0.1
jobs:
  packer-build:
    executor: packer/default
    steps:
      - checkout
      - build:
          template: ami.json
          args: '-var aws_access_key=$AWS_ACCESS_KEY \ -var aws_secret_key=$AWS_SECRET_ACCESS_KEY \ -var aws_region=us-east-1 \ -var subnet_id=subnet-20851b6d \ -var source_ami=ami-068663a3c619dd892 \ -var ssh_username=ubuntu \ -var ami_users=371394122941'
workflows:
  version: 2
  packer:
    jobs:
      - packer-build